name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 19
      uses: actions/setup-java@v1
      with:
        java-version: 19
    - name: Build plugin
      run: |
        chmod +x gradlew
        ./gradlew check buildPlugin --info
    - name: Build plugin with EAP
      run: |
        chmod +x gradlew
        export IJ_VERSION=LATEST-EAP-SNAPSHOT
        ./gradlew check buildPlugin --info
